sonar.projectKey=SmallAIOS_SmallAIOS
sonar.organization=smallaios
sonar.sources=kernel/src,security/src,onnx-rt/src,ipc/src,net/src,posix/src,container/src,bus/src
sonar.exclusions=arch/**,target/**
sonar.language=rust
