// Copyright 2026 SmallAIOS Contributors
// SPDX-License-Identifier: Apache-2.0

//! Boot-time A/B-swap conflict-scan driver.
//!
//! Spec: `openspec/changes/embedded-overlay-v1/specs/fs-overlay-syscalls/spec.md`
//! Requirement "Boot-time conflict detection".
//!
//! After every successful A/B swap into a new lower squashfs, the
//! kernel SHALL scan the upper layer and emit one
//! `overlay_conflict{ name, lower_sha3, upper_sha3 }` audit record
//! for each upper entry that shadows a name now present in the new
//! lower. This module wires the existing [`super::conflict::detect_conflicts`]
//! logic to an audit sink so the boot path can drop in one call.
//!
//! The mgmt-side audit ring is owned by another agent (see
//! `mgmt::audit` — currently a stub). To keep this module decoupled
//! we route emissions through a [`ConflictAuditSink`] trait; the
//! production wiring will substitute an `mgmt::audit::Ring` adapter.

extern crate alloc;

use alloc::string::{String, ToString};
use alloc::vec::Vec;

use smallaios_security::crypto::sha3::Sha3_256Digest;

use super::conflict::{
    detect_conflicts, ConflictMemo, ConflictReport, ConflictWarningKind, LowerManifest,
};
use super::upper_layer::{UpperError, UpperLayer};

/// One audit emission generated by the conflict scan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConflictScanEvent {
    /// `overlay_conflict{ name, lower_sha3, upper_sha3 }` per spec.
    Conflict {
        /// Upper-side name that shadows a name now in the lower.
        name: String,
        /// Lower's SHA-3-256 (from the squashfs manifest).
        lower_sha3: Sha3_256Digest,
        /// Upper's SHA-3-256 (from the sidecar).
        upper_sha3: Sha3_256Digest,
    },
    /// `overlay_conflict_warn{ name, reason }` advisory record for
    /// upper-side anomalies (missing sidecar, malformed sidecar, I/O
    /// error). Best-effort observability — not a fail-closed signal.
    Warning {
        /// Affected upper-side name.
        name: String,
        /// Short tag describing the warning.
        kind: &'static str,
    },
}

impl ConflictScanEvent {
    /// `name` of the affected entry.
    pub fn name(&self) -> &str {
        match self {
            Self::Conflict { name, .. } | Self::Warning { name, .. } => name,
        }
    }
}

/// Audit-sink trait — production wires this to the mgmt ring once
/// `mgmt::audit` lands; the test sink ([`CapturingConflictAuditSink`])
/// records each emission.
pub trait ConflictAuditSink {
    /// Append one audit event.
    fn append(&mut self, event: ConflictScanEvent);
}

/// In-memory audit-sink for tests.
#[derive(Debug, Default)]
pub struct CapturingConflictAuditSink {
    /// Events captured in append order.
    pub events: Vec<ConflictScanEvent>,
}

impl CapturingConflictAuditSink {
    /// Construct an empty sink.
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of events captured.
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// `true` iff no events have been captured.
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Number of `Conflict` (vs `Warning`) events.
    pub fn conflict_count(&self) -> usize {
        self.events
            .iter()
            .filter(|e| matches!(e, ConflictScanEvent::Conflict { .. }))
            .count()
    }
}

impl ConflictAuditSink for CapturingConflictAuditSink {
    fn append(&mut self, event: ConflictScanEvent) {
        self.events.push(event);
    }
}

fn warning_kind_tag(kind: &ConflictWarningKind) -> &'static str {
    match kind {
        ConflictWarningKind::MissingFingerprint => "missing_sidecar",
        ConflictWarningKind::MalformedFingerprint => "malformed_sidecar",
        ConflictWarningKind::Io(_) => "upper_io_error",
    }
}

/// Run a boot-time conflict scan and emit one audit event per new
/// conflict (filtered by `memo`). Warnings are emitted as advisory
/// `overlay_conflict_warn` records.
///
/// Returns the underlying [`ConflictReport`] so the boot path can
/// persist the updated memo (`memo.record(&conflict)` for each new
/// entry), then write it back to `/data/overlay/conflict-memo.toml`.
pub fn run_boot_conflict_scan<U, M, A>(
    upper: &U,
    lower: &M,
    memo: &ConflictMemo,
    audit: &mut A,
) -> Result<ConflictReport, UpperError>
where
    U: UpperLayer,
    M: LowerManifest,
    A: ConflictAuditSink + ?Sized,
{
    let report = detect_conflicts(upper, lower, memo)?;

    for c in &report.new_conflicts {
        audit.append(ConflictScanEvent::Conflict {
            name: c.name.clone(),
            lower_sha3: c.lower_sha3,
            upper_sha3: c.upper_sha3,
        });
    }
    for w in &report.warnings {
        audit.append(ConflictScanEvent::Warning {
            name: w.name.clone(),
            kind: warning_kind_tag(&w.reason),
        });
    }
    Ok(report)
}

/// Convenience: trim every emitted conflict's name to its display
/// form (no path components since the upper is flat). Mostly here so
/// the operator can use `String::push_str` on it.
pub fn name_for_audit(name: &str) -> String {
    name.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::overlay::conflict::{MapLowerManifest, OverlayConflict};
    use crate::overlay::integrity::{encode_sidecar_bytes, hash_bytes, sha3_sidecar_path};
    use crate::overlay::upper_layer::MockUpperLayer;

    fn upper_with_files(entries: &[(&str, &[u8])]) -> MockUpperLayer {
        let mut u = MockUpperLayer::new();
        for (name, bytes) in entries {
            u.add_file(name, bytes);
            // Add a sidecar with the actual digest.
            let digest = hash_bytes(bytes);
            let sc = encode_sidecar_bytes(&digest);
            u.add_file(&sha3_sidecar_path(name), &sc);
        }
        u
    }

    #[test]
    fn no_conflicts_emits_nothing() {
        let upper = upper_with_files(&[("alpha.onnx", b"hello")]);
        let lower = MapLowerManifest::new();
        let memo = ConflictMemo::new();
        let mut audit = CapturingConflictAuditSink::new();
        let report = run_boot_conflict_scan(&upper, &lower, &memo, &mut audit).unwrap();
        assert_eq!(report.new_conflicts.len(), 0);
        assert!(audit.is_empty());
    }

    #[test]
    fn new_conflict_emits_one_audit_event() {
        let upper_bytes = b"upper-bytes";
        let upper = upper_with_files(&[("conflict.onnx", upper_bytes)]);
        let mut lower = MapLowerManifest::new();
        let lower_digest = hash_bytes(b"lower-bytes");
        lower.insert("conflict.onnx", lower_digest);

        let memo = ConflictMemo::new();
        let mut audit = CapturingConflictAuditSink::new();
        let report = run_boot_conflict_scan(&upper, &lower, &memo, &mut audit).unwrap();

        assert_eq!(report.new_conflicts.len(), 1);
        assert_eq!(audit.conflict_count(), 1);
        match &audit.events[0] {
            ConflictScanEvent::Conflict {
                name,
                lower_sha3,
                upper_sha3,
            } => {
                assert_eq!(name, "conflict.onnx");
                assert_eq!(*lower_sha3, lower_digest);
                assert_eq!(*upper_sha3, hash_bytes(upper_bytes));
            }
            _ => panic!("expected Conflict event"),
        }
    }

    #[test]
    fn pre_existing_conflict_is_suppressed_by_memo() {
        let upper_bytes = b"upper-bytes";
        let upper = upper_with_files(&[("c.onnx", upper_bytes)]);
        let mut lower = MapLowerManifest::new();
        let lower_digest = hash_bytes(b"lower-bytes");
        lower.insert("c.onnx", lower_digest);
        let upper_digest = hash_bytes(upper_bytes);

        // Memo claims this conflict was already audited last boot.
        let mut memo = ConflictMemo::new();
        memo.record(&OverlayConflict {
            name: "c.onnx".to_string(),
            lower_sha3: lower_digest,
            upper_sha3: upper_digest,
        });

        let mut audit = CapturingConflictAuditSink::new();
        let _ = run_boot_conflict_scan(&upper, &lower, &memo, &mut audit).unwrap();

        // No new audit event — suppressed by memo.
        assert_eq!(audit.conflict_count(), 0);
    }

    #[test]
    fn audit_event_name_helper_returns_inner_name() {
        let e = ConflictScanEvent::Warning {
            name: "x".to_string(),
            kind: "missing_sidecar",
        };
        assert_eq!(e.name(), "x");
        let e = ConflictScanEvent::Conflict {
            name: "y".to_string(),
            lower_sha3: Sha3_256Digest::from_bytes([0; 32]),
            upper_sha3: Sha3_256Digest::from_bytes([0; 32]),
        };
        assert_eq!(e.name(), "y");
    }

    #[test]
    fn warning_kind_tag_covers_each_variant() {
        assert_eq!(
            warning_kind_tag(&ConflictWarningKind::MissingFingerprint),
            "missing_sidecar"
        );
        assert_eq!(
            warning_kind_tag(&ConflictWarningKind::MalformedFingerprint),
            "malformed_sidecar"
        );
    }
}
