#!/bin/bash
# SmallAIOS Network Boot Deploy Script
# SPDX-License-Identifier: Apache-2.0
#
# Sets up TFTP server and deploys SmallAIOS kernel for network boot.
#
# Usage:
#   ./scripts/deploy-netboot.sh setup --server-ip 192.168.1.100  # One-time TFTP setup
#   ./scripts/deploy-netboot.sh deploy                            # Build + copy to TFTP
#   ./scripts/deploy-netboot.sh deploy --skip-build               # Copy existing binary

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TFTP_ROOT="/srv/tftp/smallaios"
KERNEL_NAME="smallaios-aarch64"
TARGET="aarch64-unknown-none"
PACKAGE="smallaios-arch-aarch64"
BUILD_STD="-Z build-std=core,compiler_builtins,alloc -Z build-std-features=compiler-builtins-mem"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[netboot]${NC} $*"; }
warn()  { echo -e "${YELLOW}[netboot]${NC} $*"; }
error() { echo -e "${RED}[netboot]${NC} $*" >&2; }

usage() {
    cat <<EOF
Usage: $(basename "$0") <command> [options]

Commands:
  setup    One-time TFTP server setup (requires sudo)
  deploy   Build and copy kernel to TFTP directory

Options for setup:
  --server-ip IP    IP address of this server (required)
  --dhcp-range R    DHCP range for dev subnet (optional, e.g. 192.168.99.50,192.168.99.100)
  --tftp-only       Don't configure DHCP, just TFTP (default if --dhcp-range not given)

Options for deploy:
  --skip-build      Don't rebuild, just copy existing binary
  --debug           Deploy debug build instead of release
  --target TARGET   Override target triple (default: $TARGET)
EOF
}

setup_tftp() {
    local server_ip=""
    local dhcp_range=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --server-ip) server_ip="$2"; shift 2 ;;
            --dhcp-range) dhcp_range="$2"; shift 2 ;;
            --tftp-only) shift ;;
            *) error "Unknown option: $1"; usage; exit 1 ;;
        esac
    done

    if [[ -z "$server_ip" ]]; then
        error "--server-ip is required"
        usage
        exit 1
    fi

    if [[ $EUID -ne 0 ]]; then
        error "Setup requires root. Run with: sudo $0 setup --server-ip $server_ip"
        exit 1
    fi

    info "Installing dnsmasq..."
    if command -v apt-get &>/dev/null; then
        apt-get install -y dnsmasq
    elif command -v dnf &>/dev/null; then
        dnf install -y dnsmasq
    elif command -v pacman &>/dev/null; then
        pacman -S --noconfirm dnsmasq
    else
        error "Unsupported package manager. Install dnsmasq manually."
        exit 1
    fi

    info "Creating TFTP directory: $TFTP_ROOT"
    mkdir -p "$TFTP_ROOT"

    info "Writing dnsmasq configuration..."
    local dnsmasq_conf="/etc/dnsmasq.d/smallaios-netboot.conf"
    mkdir -p /etc/dnsmasq.d

    cat > "$dnsmasq_conf" <<CONF
# SmallAIOS Network Boot Configuration
# Generated by deploy-netboot.sh

# TFTP server
enable-tftp
tftp-root=$TFTP_ROOT
tftp-secure

# Logging
log-queries
log-dhcp
log-facility=/var/log/smallaios-netboot.log
CONF

    if [[ -n "$dhcp_range" ]]; then
        cat >> "$dnsmasq_conf" <<CONF

# DHCP for dev subnet
dhcp-range=$dhcp_range,12h
dhcp-option=66,$server_ip

# PXE boot filename (UEFI ARM64)
dhcp-boot=$KERNEL_NAME
CONF
        info "DHCP enabled with range: $dhcp_range"
    else
        info "TFTP-only mode (no DHCP). Board must be configured to point to $server_ip."
    fi

    # Ensure dnsmasq includes the conf.d directory
    if ! grep -q "^conf-dir=/etc/dnsmasq.d" /etc/dnsmasq.conf 2>/dev/null; then
        echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> /etc/dnsmasq.conf
    fi

    info "Restarting dnsmasq..."
    systemctl enable dnsmasq
    systemctl restart dnsmasq

    info "TFTP server ready at $server_ip"
    info "Deploy kernels to: $TFTP_ROOT/"
    info ""
    info "Board configuration:"
    info "  RPi UEFI:  Set PXE boot, TFTP server = $server_ip"
    info "  Jetson:    setenv serverip $server_ip; saveenv"
}

deploy_kernel() {
    local skip_build=false
    local build_type="release"
    local target="$TARGET"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --skip-build) skip_build=true; shift ;;
            --debug) build_type="debug"; shift ;;
            --target) target="$2"; shift 2 ;;
            *) error "Unknown option: $1"; usage; exit 1 ;;
        esac
    done

    cd "$PROJECT_DIR"

    if [[ "$skip_build" == "false" ]]; then
        info "Building SmallAIOS for $target ($build_type)..."
        local build_flags=""
        if [[ "$build_type" == "release" ]]; then
            build_flags="--release"
        fi
        # shellcheck disable=SC2086
        cargo build $build_flags --target "$target" -p "$PACKAGE" $BUILD_STD
    fi

    local kernel_path="target/$target/$build_type/$KERNEL_NAME"
    if [[ ! -f "$kernel_path" ]]; then
        error "Kernel not found at: $kernel_path"
        error "Did you build first? Run without --skip-build"
        exit 1
    fi

    local kernel_size
    kernel_size=$(stat -c%s "$kernel_path" 2>/dev/null || stat -f%z "$kernel_path")
    info "Kernel size: $(( kernel_size / 1024 )) KiB"

    if [[ ! -d "$TFTP_ROOT" ]]; then
        error "TFTP root not found: $TFTP_ROOT"
        error "Run 'sudo $0 setup --server-ip <ip>' first"
        exit 1
    fi

    info "Copying to $TFTP_ROOT/$KERNEL_NAME ..."
    sudo cp "$kernel_path" "$TFTP_ROOT/$KERNEL_NAME"
    sudo chmod 644 "$TFTP_ROOT/$KERNEL_NAME"

    info "Deploy complete. Reboot the board to pick up the new kernel."
    info ""
    info "Watch serial console:  make serial DEV=/dev/ttyUSB0"
    info "Watch TFTP requests:   sudo journalctl -f -u dnsmasq"
}

case "${1:-}" in
    setup)  shift; setup_tftp "$@" ;;
    deploy) shift; deploy_kernel "$@" ;;
    *)      usage; exit 1 ;;
esac
