[package]
name = "smallaios-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "SmallAIOS networking: IPv4/IPv6, TCP/UDP, QUIC/HTTP3, TLS 1.3"

[features]
default = ["ipv4", "ipv6", "quic"]
ipv4 = []
ipv6 = []
quic = []
rtl8169 = []
dhcp = []
static-ip = []
tegra-net = ["rtl8169", "dhcp", "static-ip"]

[dependencies]
smallaios-kernel = { path = "../kernel" }
